group:
  - files:
      - source: _extensions/r3-theme/
        dest: _extensions/rostools/r3-theme/
    repos: |
      rostools/r-cubed
      rostools/r-cubed-advanced
      rostools/r-cubed-intermediate
      rostools/r-cubed-intro
      rostools/guides
