group:
  - files:
      - source: _extensions/r3-theme/
        dest: _extensions/rostools/r3-theme/
        deleteOrphaned: true
      - source: .github/workflows/
        dest: .github/workflows/
        deleteOrphaned: true
      - source: .vscode/
        dest: .vscode/
        deleteOrphaned: true
      - source: justfile
        dest: justfile
      - source: .gitignore
        dest: .gitignore
    repos: |
      rostools/coding-club
      rostools/r-cubed
      rostools/cog-flow-intro
      rostools/r-cubed-advanced
      rostools/r-cubed-intermediate
      rostools/r-cubed-intro
      rostools/guides
