project:
  type: r3-theme
  # pre-render: bash _build-slides.sh
  # resources:
  #   - slides/*.html

book:
  title: Testing
  author: Luke W. Johnston
  date: last-modified
  repo-url: https://github.com/rostools/r-cubed
  chapters:
    - index.qmd
    - part: "Preamble"
      chapters:
      - preamble/syllabus.qmd
      - preamble/schedule.qmd
      - preamble/pre-course.qmd
    - part: "Sessions"
      chapters:
      - sessions/introduction.qmd
      - sessions/lesson.qmd
      - sessions/what-next.qmd
  appendices:
    - appendix/social.qmd
    - appendix/for-instructors.qmd
    - appendix/references.qmd
    # - LICENSE.md

format:
  r3-theme-html: default

editor_options:
  markdown:
    wrap: 72
    canonical: true
