project:
  type: r3-theme
  # pre-render: quarto render slides/*.qmd
  # resources:
  #   - slides/*.html

book:
  title: Testing
  author: Luke W. Johnston and Signe Kirk Brødbæk
  date: last-modified
  repo-url: https://github.com/rostools/REPO
  site-url: https://REPO.rostools.org/
  body-header: "{{< text_snippet wip >}}"
  chapters:
    - index.qmd
    - part: "Preamble"
      chapters:
      - preamble/syllabus.qmd
      - preamble/schedule.qmd
      - preamble/pre-workshop.qmd
    - part: "Sessions"
      chapters:
      - sessions/introduction.qmd
      - sessions/lesson.qmd
      - sessions/what-next.qmd
  appendices:
    - appendix/social.qmd
    - appendix/for-teachers.qmd
    - appendix/references.qmd
  page-footer:
    center:
      - text: "License: CC BY 4.0 {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}}"
        href: LICENSE.html
      - text: "Code of Conduct"
        href: "https://guides.rostools.org/conduct.html"

format:
  r3-theme-html: default

editor:
  markdown:
    wrap: 72
    canonical: true
